# -*- coding: utf-8 -*-
"""halo_dunia.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DFbz3BwNeQd4SPvMSDhC-QcCbBZ_rk43
"""

print ('Halo Dunia !')